routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->prefix('admin')->group(function () {
    // Route::get('/', function () {
    //     return view('admin.layouts.default',['flag' => 'dashboard']);
    // })->name('dashboard');
    Route::resource('nation', 'NationController');
    Route::resource('purpose', 'PurposeController');
    Route::resource('type', 'TypeController');
    Route::resource('processing', 'ProcessingController');
    Route::resource('customer', 'CustomerController');
    Route::get('customer/detail/{id}', 'CustomerController@detailOrder')->name('detailOrder');

    Route::post('/visa/update-status/{id}', 'CustomerController@updateStatus')->name('update-status');
    Route::get('/gallery', function () {
        return view('admin.gallery',['flag' => 'gallery']);
    })->name('gallery');

    //theme option
    
    Route::prefix('theme-option')->group(function () {
        Route::get('/list', 'ThemeoptionController@indexHeader')->name('indexHeader');
        Route::get('/edit', 'ThemeoptionController@indexEdit')->name('indeEdit');
        Route::post('/edit', 'ThemeoptionController@postEdit')->name('edit-theme');
        
    });
   
});

Auth::routes();
Route::post('/step-3.html', 'HomeController@createVisa')->name('create-visa');
Route::post('/step-4.html', 'HomeController@updateVisa')->name('update-visa');
Route::get('/index.html', 'HomeController@index')->name('index');
Route::get('/', 'HomeController@index')->name('home');
Route::post('/step-1.html', 'HomeController@step1')->name('step-1');
Route::get('/step-2-evisa.html', 'HomeController@step2')->name('evisa-step-2');
Route::get('/step-2-evisa-arrival.html', 'HomeController@step2_arrival')->name('evisa-arrival-step-2');
Route::get('/procedure-instructions.html', 'HomeController@procedure')->name('procedure-instructions');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/404', function () {
        return view('errors.404',['flag' => '']);
})->name('error-404');
Route::get('/500', function () {
        return view('errors.500',['flag' => '']);
})->name('error-500');

app/Processing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Processing extends Model
{
    //
    protected $fillable = [
        'name', 'value', 'status',"type_evisa","type_visa_arrival",
    ];
}

app/Http/Controllers/ProcessingController.php
<?php

namespace App\Http\Controllers;

use App\Processing;
use Illuminate\Http\Request;
use App\Http\Requests\ProcessingRequest as ProcessingRequest;
use Session;

class ProcessingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $objs = Processing::all();
        return view('admin.processing.list',['objs'=>$objs]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.processing.create',['route_action'=>route('processing.store')]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProcessingRequest $request)
    {
        $input=$request->all();
        if($input["typevisa"]==="1")
        {
            $input["type_evisa"]=1;
        }
        else if($input["typevisa"]==="2")
        {
            $input["type_visa_arrival"]=1;
        }
        else
        {
            $input["type_evisa"]=1;
            $input["type_visa_arrival"]=1;
        }
        Processing::create($input);
        Session::flash('success-processing', 'Tạo mới processing : "'.$input['name'].'" thành công.');
        return redirect()->route('processing.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Nation  $nation
     * @return \Illuminate\Http\Response
     */
    public function show(Nation $nation)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Nation  $nation
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $obj = Processing::find($id);
        if($obj == null){
            Session::flash('error-processing', 'Không tìm thấy dữ liệu.');  
            return redirect()->route('processing.index');  
        }
        return view('admin.processing.edit',['obj'=>$obj, 
                    'route_action'=>route('processing.update',['id'=>$id])]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Nation  $nation
     * @return \Illuminate\Http\Response
     */
    public function update(ProcessingRequest $request, $id)
    {
        //
        $obj = Processing::find($id);
        if($obj == null){
            Session::flash('error-processing', 'Không tìm thấy dữ liệu.');  
            return redirect()->route('processing.index');  
        }
        $input=$request->all();
        if($input["typevisa"]==="1")
        {
            $input["type_evisa"]=1;
            $input["type_visa_arrival"]=0;
        }
        else if($input["typevisa"]==="2")
        {
            $input["type_visa_arrival"]=1;
            $input["type_evisa"]=0;
        }
        else
        {
            $input["type_evisa"]=1;
            $input["type_visa_arrival"]=1;
        }
        $obj->update($input);
        Session::flash('success-processing', 'Cập nhật dữ liệu thành công.'); 
        return redirect()->route('processing.edit',['id'=>$id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Nation  $nation
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $obj = Processing::find($id);
        if($obj == null){
            Session::flash('error-processing', 'Không tìm thấy dữ liệu.');  
            return redirect()->route('processing.index');  
        }
        $obj->delete();
        Session::flash('success-processing', 'Xóa dữ liệu thành công.');  
        return redirect()->route('processing.index');  
    }
}

resources/views/admin/processing/create.blade.php
@extends('admin.layouts.form-default')

@section('css')
@endsection

@section('content')
@include('admin.processing.form')
@endsection

@section('js')
@endsection

resources/views/admin/processing/edit.blade.php
@extends('admin.layouts.form-default')

@section('css')
@endsection

@section('content')
@include('admin.processing.form')
@endsection

@section('js')
@endsection

resources/views/admin/processing/form.blade.php
@if(session('error-processing'))
<div class="alert alert-danger">
	<strong>{{session('error-processing')}}</strong>
</div>
@endif
@if(session('success-processing'))
<div class="alert alert-success">
	<strong>{{session('success-processing')}}</strong>
</div>
@endif
<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
	<label class="col-sm-2 control-label">Tên (*) </label>
	<div class="col-sm-4">
		<input type="text" class="form-control" name="name" id="name" 
		value="{{isset($obj) ? $obj->name : old('name')}}" required>
	</div>
</div>
<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
	<label class="col-sm-2 control-label">Loại (*) </label>
	<div class="col-sm-2">
		<div class="radio">
			<label>
			  <input type="radio" name="typevisa"  value="1" 
				@if(isset($obj) && $obj->type_evisa==1 && $obj->type_visa_arrival !=1)
					checked
				@endif
			  >
			  Evisa
			</label>
		</div>
	</div>
	<div class="col-sm-2">
		<div class="radio">
			<label>
			  <input type="radio" name="typevisa"  value="2"
			  	@if(isset($obj) && $obj->type_visa_arrival==1 && $obj->type_evisa != 1)
					checked
				@endif
			  >
			  Visa cửa khẩu
			</label>
		</div>
	</div>
	<div class="col-sm-2">
		<div class="radio">
			<label>
			  <input type="radio" name="typevisa" value="3" 
			  	@if(isset($obj) && $obj->type_visa_arrival == 1 && $obj->type_evisa==1)
					checked
				@elseif(!isset($obj) )
					checked
				@endif
			  >
			 Cả 2 loại
			</label>
		</div>
	</div>
</div>
<div class="form-group {{ $errors->has('value') ? 'has-error' : '' }}">
	<label class="col-sm-2 control-label">Giá trị (*) </label>
	<div class="col-sm-4">
		<input type="number" min="0" class="form-control" name="value" id="value" 
		value="{{isset($obj) ? $obj->value : old('value')}}" required>
	</div>
</div>
@include('admin.partials.status')

resources/views/admin/processing/list.blade.php
@extends('admin.layouts.table-default')

@section('css')
@endsection

@section('content')
@if(session('error-processing'))
<div class="alert alert-danger">
	<strong>{{session('error-processing')}}</strong>
</div>
@endif
@if(session('success-processing'))
<div class="alert alert-success">
	<strong>{{session('success-processing')}}</strong>
</div>
@endif

<div class="table-responsive">
<table class="table table-striped table-bordered table-hover dataTables-example">
<thead style="color: #000;font-weight: bold;">
	<tr>
		<td class="text-center">ID</td>
		<td class="text-center">Tên</td>
		<td class="text-center">Value</td>
		<td class="text-center">Type</td>
		<td class="text-center">Trạng thái</td>
		<td class="text-center"></td>
	</tr>
</thead>
<tbody>
	@foreach($objs as $obj)
	<tr>
		<td class="text-center">{{$obj->id}}</td>
		<td class="text-center">{{$obj->name}}</td>
		<td class="text-center">{{$obj->value}}</td>
		<td class="text-center">
			@if($obj->type_evisa == 1 && $obj->type_visa_arrival !=1)
				<span class="badge badge-success">Evisa</span>
			@elseif($obj->type_evisa != 1 && $obj->type_visa_arrival ==1)
				<span class="badge badge-success">Visa cửa khẩu</span>
			@else
				<span class="badge badge-success">Cả 2 loại</span> 
			@endif
		</td>
		<td class="text-center">
			@if($obj->status == 1)
				<span class="badge badge-success">Sử dụng</span>
			@else
				<span class="badge badge-danger">Không sử dụng</span> 
			@endif
		</td>
		<td class="text-center">
			<form action="{{route('processing.edit', ['id' => $obj->id])}}">
				<button class="btn btn-warning btn-sm" type="submit">
						Sửa
				<span class="fa fa-edit" data-fa-transform="shrink-3"></span>
				</button>
				<button class="btn btn-danger btn-sm delete-button" 
					data-action ="{{ route('processing.destroy',$obj->id) }}" type="button">
						Xóa
				<span class="fa fa-trash" data-fa-transform="shrink-3"></span>
				</button>	
			</form>
		</td>
	</tr>
	@endforeach
</tbody>
</table>
</div>
@endsection

@section('js')
@endsection