routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->prefix('admin')->group(function () {
    // Route::get('/', function () {
    //     return view('admin.layouts.default',['flag' => 'dashboard']);
    // })->name('dashboard');
    Route::resource('nation', 'NationController');
    Route::resource('purpose', 'PurposeController');
    Route::resource('type', 'TypeController');
    Route::resource('processing', 'ProcessingController');
    Route::resource('customer', 'CustomerController');
    Route::get('customer/detail/{id}', 'CustomerController@detailOrder')->name('detailOrder');

    Route::post('/visa/update-status/{id}', 'CustomerController@updateStatus')->name('update-status');
    Route::get('/gallery', function () {
        return view('admin.gallery',['flag' => 'gallery']);
    })->name('gallery');

    //theme option
    
    Route::prefix('theme-option')->group(function () {
        Route::get('/list', 'ThemeoptionController@indexHeader')->name('indexHeader');
        Route::get('/edit', 'ThemeoptionController@indexEdit')->name('indeEdit');
        Route::post('/edit', 'ThemeoptionController@postEdit')->name('edit-theme');
        
    });
   
});

Auth::routes();
Route::post('/step-3.html', 'HomeController@createVisa')->name('create-visa');
Route::post('/step-4.html', 'HomeController@updateVisa')->name('update-visa');
Route::get('/index.html', 'HomeController@index')->name('index');
Route::get('/', 'HomeController@index')->name('home');
Route::post('/step-1.html', 'HomeController@step1')->name('step-1');
Route::get('/step-2-evisa.html', 'HomeController@step2')->name('evisa-step-2');
Route::get('/step-2-evisa-arrival.html', 'HomeController@step2_arrival')->name('evisa-arrival-step-2');
Route::get('/procedure-instructions.html', 'HomeController@procedure')->name('procedure-instructions');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/404', function () {
        return view('errors.404',['flag' => '']);
})->name('error-404');
Route::get('/500', function () {
        return view('errors.500',['flag' => '']);
})->name('error-500');

resources/views/admin/partials/breadcrumb-form.blade.php
{{-- Breadcrumb --}}
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
        <h2>{{$title}}</h2>
        <ol class="breadcrumb">
	        <li>
	            <a href="#">Bảng tin</a>
	        </li>
	        <li>
	            <a href="{{$route_list}}">Danh sách</a>
	        </li>
	        <li class="active">
	            <strong>{{$title}}</strong>
	        </li>
        </ol>
    </div>
</div>
{{-- END Breadcrumb --}}

resources/views/admin/partials/breadcrumb-table.blade.php
<div class="row wrapper border-bottom white-bg page-heading">
	<div class="col-sm-4">
		<h2>{{$title}}</h2>
		<ol class="breadcrumb">
			<li>
				<a href="#">Bảng tin</a>
			</li>
			<li class="active">
				<strong>{{$title}}</strong>
			</li>
		</ol>
	</div>
	<div class="col-sm-8">
		<div class="title-action">
			<a href="{{$route_create}}" class="btn btn-primary">Thêm mới</a>
		</div>
	</div>
</div>

resources/views/admin/partials/error-list.blade.php
@if(count($errors) > 0)
<div class="alert alert-danger">
	@foreach($errors->all() as $err)
	<strong>{{$err}}</strong><br>
	@endforeach
</div>
@endif

resources/views/admin/partials/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<title>{{$title}}</title>

<link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/font-awesome/css/font-awesome.css')}}" rel="stylesheet">
<link href="{{asset('assets/css/style.css')}}" rel="stylesheet">

resources/views/admin/partials/left-side-bar.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            @include('admin.partials.navbar-left.nav-header')
            <li class={{$flag == "bangtin" ? "active" : ""}}>
                <a href="#"><i class="fa fa-th-large"></i> <span class="nav-label">Bảng tin</span></span></a>
            </li>
            <li class={{$flag == "customer" ? "active" : ""}}>
                <a href="{{route('customer.index')}}"><i class="fa fa-picture-o"></i> <span class="nav-label">Danh sách yêu cầu</span></a>
            </li>
            <li class={{$flag == "nation" ? "active" : ""}}>
                <a href="{{route('nation.index')}}"><i class="fa fa-picture-o"></i> <span class="nav-label">Nationality</span></a>
            </li>
            <li class={{$flag == "purpose" ? "active" : ""}}>
                <a href="{{route('purpose.index')}}"><i class="fa fa-picture-o"></i> <span class="nav-label">Purpose of Visa</span></a>
            </li>
            <li class={{$flag == "type" ? "active" : ""}}>
                <a href="{{route('type.index')}}"><i class="fa fa-picture-o"></i> <span class="nav-label">Type of Visa</span></a>
            </li>
            <li class={{$flag == "processing" ? "active" : ""}}>
                <a href="{{route('processing.index')}}"><i class="fa fa-picture-o"></i> <span class="nav-label">Processing Time</span></a>
            </li>
            <li class={{$flag == "files" ? "active" : ""}}>
                <a href="{{route('gallery')}}"><i class="fa fa-picture-o"></i> <span class="nav-label">Files</span></a>
            </li>
            <li class={{$flag == "header" ? "active" : ""}}>
                    <a href="{{route('indexHeader')}}"><i class="fa fa-picture-o"></i> <span class="nav-label">Theme Option</span></a>
            </li>
            <li class="landing_link">
                <a target="_blank" href="{{config('website.domain')}}"><i class="fa fa-star"></i> <span class="nav-label">Website</span> <span class="label label-warning pull-right"></span></a>
            </li>
        </ul>
    </div>
</nav>

resources/views/admin/partials/scripts.blade.php
<!-- Mainly scripts -->
<script src="{{asset('assets/js/jquery-2.1.1.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/plugins/metisMenu/jquery.metisMenu.js')}}"></script>
<script src="{{asset('assets/js/plugins/slimscroll/jquery.slimscroll.min.js')}}"></script>

<!-- Flot -->
<script src="{{asset('assets/js/plugins/flot/jquery.flot.js')}}"></script>
<script src="{{asset('assets/js/plugins/flot/jquery.flot.tooltip.min.js')}}"></script>
<script src="{{asset('assets/js/plugins/flot/jquery.flot.spline.js')}}"></script>
<script src="{{asset('assets/js/plugins/flot/jquery.flot.resize.js')}}"></script>
<script src="{{asset('assets/js/plugins/flot/jquery.flot.pie.js')}}"></script>

<!-- Peity -->
<script src="{{asset('assets/js/plugins/peity/jquery.peity.min.js')}}"></script>
<script src="{{asset('assets/js/demo/peity-demo.js')}}"></script>

<!-- Custom and plugin javascript -->
<script src="{{asset('assets/js/inspinia.js')}}"></script>
<script src="{{asset('assets/js/plugins/pace/pace.min.js')}}"></script>

<!-- jQuery UI -->
<script src="{{asset('assets/js/plugins/jquery-ui/jquery-ui.min.js')}}"></script>

<!-- GITTER -->
<script src="{{asset('assets/js/plugins/gritter/jquery.gritter.min.js')}}"></script>

<!-- Sparkline -->
<script src="{{asset('assets/js/plugins/sparkline/jquery.sparkline.min.js')}}"></script>

<!-- Sparkline demo data  -->
<script src="{{asset('assets/js/demo/sparkline-demo.js')}}"></script>

<!-- ChartJS-->
<script src="{{asset('assets/js/plugins/chartJs/Chart.min.js')}}"></script>

<!-- Toastr -->
<script src="{{asset('assets/js/plugins/toastr/toastr.min.js')}}"></script>

resources/views/admin/partials/status.blade.php
<div class="form-group">
	<label class="col-sm-2 control-label">Trạng thái (*)</label>
	<div class="col-md-4">
		@if(!isset($obj))
			<select class="form-control m-b" name="status">
				<option value="1" {{old('status') == "1" ? "selected" : ""}}>Sử dụng</option>
				<option value="0" {{old('status') == "0" ? "selected" : ""}}>Không sử dụng</option>
			</select> 
		@else
			<select class="form-control m-b" name="status">
				<option value="1" {{$obj->status == "1" ? "selected" : ""}}>Sử dụng</option>
				<option value="0" {{$obj->status == "0" ? "selected" : ""}}>Không sử dụng</option>
			</select>
		@endif                                       
	</div>
</div>

resources/views/admin/partials/top-bar.blade.php
<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        <form role="search" class="navbar-form-custom" action="#">
            <div class="form-group">
                <input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
            </div>
        </form>
    </div>
    <ul class="nav navbar-top-links navbar-right">
        <li>
            <a href="{{ route('logout') }}"  onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
                </form>
                <i class="fa fa-sign-out"></i> Đăng xuất
            </a>
        </li>
    </ul>
</nav>